/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Generator config
 */
export interface Config {
  /**
   * Source Squid Archive for a network that supports 'contracts' pallet. Can be a URL or an alias. See docs.subsquid.io/archives/overview.
   */
  archive: string;
  /**
   * ContractJSONs defining the exact data to extract from each contract.
   */
  contracts: {
    /**
     * Contract name.
     */
    name?: string;
    /**
     * Contract address.
     */
    address: string;
    /**
     * Path to the contract JSON ABI.
     */
    abi: string;
    /**
     * One or multiple contract events to be indexed. true indexes all events defined in the ABI; false indexes none. Default: false.
     */
    events?: string[] | boolean;
    /**
     * Range of blocks to index. Default: all from the genesis.
     */
    range?: {
      from?: number;
      to?: number;
    };
  }[];
}
